package com.speedevand.inkride.core.database

import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import assertk.assertThat
import assertk.assertions.containsExactly
import assertk.assertions.hasSize
import assertk.assertions.isEqualTo
import assertk.assertions.isGreaterThan
import kotlinx.coroutines.test.runTest
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class BikeProfileDaoTest : DatabaseTestBase() {
    private val dao: BikeProfileDao get() = db.bikeProfileDao()

    @Test
    fun upsertWithZeroIdInsertsAndReturnsTheGeneratedId() =
        runTest {
            val inserted = TestEntities.bikeProfile(name = "Road bike")
            val id = dao.upsert(inserted)

            assertThat(id).isGreaterThan(0L)
            dao.observeAll().test {
                val stored = awaitItem().single()
                assertThat(stored.id).isEqualTo(id)
                assertThat(stored.name).isEqualTo("Road bike")
                // Whole-entity comparison: catches a transposition between, e.g.,
                // weightKg and any other column.
                assertThat(stored).isEqualTo(inserted.copy(id = id))
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun upsertWithAnExistingIdReplacesInPlaceRatherThanAddingARow() =
        runTest {
            val id = dao.upsert(TestEntities.bikeProfile(name = "Road bike"))

            val returnedId =
                dao.upsert(TestEntities.bikeProfile(id = id, name = "Road bike v2", weightKg = 7.9))

            assertThat(returnedId).isEqualTo(id)
            dao.observeAll().test {
                val all = awaitItem()
                assertThat(all).hasSize(1)
                assertThat(all.single().name).isEqualTo("Road bike v2")
                assertThat(all.single().weightKg).isEqualTo(7.9)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun observeAllEmitsProfilesOrderedByIdAscending() =
        runTest {
            // Insert the higher id first, so insertion order and id order disagree.
            // With autogenerated ids they would always agree, and the test could not
            // tell `ORDER BY id ASC` apart from "whatever order rows went in".
            dao.upsert(TestEntities.bikeProfile(id = 5L, name = "MTB", type = "MTB"))
            dao.upsert(TestEntities.bikeProfile(id = 2L, name = "Road bike"))

            dao.observeAll().test {
                assertThat(awaitItem().map { it.id }).containsExactly(2L, 5L)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun observeAllReEmitsAfterADelete() =
        runTest {
            val id = dao.upsert(TestEntities.bikeProfile())

            dao.observeAll().test {
                assertThat(awaitItem()).hasSize(1)

                dao.deleteById(id)

                assertThat(awaitItem()).hasSize(0)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun deleteByIdRemovesOnlyThatProfile() =
        runTest {
            val keptId = dao.upsert(TestEntities.bikeProfile(name = "Road bike"))
            val doomedId = dao.upsert(TestEntities.bikeProfile(name = "MTB", type = "MTB"))

            dao.deleteById(doomedId)

            dao.observeAll().test {
                assertThat(awaitItem().map { it.id }).containsExactly(keptId)
                cancelAndIgnoreRemainingEvents()
            }
        }
}
